### ISSUE TITLE
Issue with using Dashbot

### ISSUE THREAD

**Issue by Trudeaucj** [howdyai/botkit-starter-slack#1]
```info: [Start]  0  Task for  <User> in <Team>
info: >   [Start]  0  Conversation with  <User> in <Team>
~/dev/botkit-starter-slack/node_modules/botkit/lib/CoreBot.js:1017
                worker.send(message, cb);
                      ^

TypeError: Cannot read property 'send' of undefined
```

When using the Dashbot middleware causing somewhere inside botkit to not have a proper bot object. Once you stop using dashbot everything works properly.

**Comment by benbrown** [comment]
This was due to the starter kit's oauth implementation not setting some fields that are used by dashbot.  Fixed!
