### ISSUE TITLE
With mongo storage  bot is not responding

### ISSUE THREAD

**Issue by abidhkhan** [howdyai/botkit-starter-slack#13]
I am trying to use mongo. However once i define storage configuration in .env file, by bot become unresponsive.  With json file system it is working properly. I am using below mongo URI in .enf file.

> MONGO_URI=mongodb://127.0.0.1:27017/jira

**Comment by wlaoh** [comment]
I ran into this issue as well.  For some reason after connecting to the MongoDB I had to go to http://localhost:3000 or whatever your bot url is with port 3000 and accept oauth again, then it will start working.

**Comment by starpause** [comment]
So what happens here is that when you initialize the bot with a different data store than mongo, all of the bot's config etc are set up in that other storage. When you switch over to the new storage without re-installing the bot on your slack instance, it will have a blank config and not know what to do. wlaoh's answer is the quickest fix for this.
