### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by shakyink** [howdyai/botkit-starter-slack#15]
The project could benefit from a Contribution Guide. Adding a project Contribution Guide can help get more developers pushing meaningful change to the project.

**Comment by peterswimm** [comment]
We accept contributions on the main OSS Botkit project here:
https://github.com/howdyai/botkit/blob/master/CONTRIBUTING.md

Starter kits are largely a product of Howdy to get people up on a given platform quickly, and are curated by us to have the best possible experience, although we will certainly entertain requests!

**Comment by shakyink** [comment]
👍
