### ISSUE TITLE
Deploy starter kit on google cloud platform

### ISSUE THREAD

**Issue by RomeHein** [howdyai/botkit-starter-slack#17]
Hey there!

First thanks for your amazing work!
I'm having some difficulties to deploy the starter kit on google cloud platform. I've fallowed this tutorial:
https://codelabs.developers.google.com/codelabs/cloud-slack-bot/index.html#0
and this tutorial to deploy express server:
https://codelabs.developers.google.com/codelabs/cloud-app-engine-node/index.html?index=..%2F..%2Findex#0

Once running, I can access to the index page, when I click the add to slack button it's working (except when I press the authorize button, but it's due to the fallowing issue). 
But the issue is when I go on my slack account and add the fallowing url to the Enable Event Api section:
http://my-test-project.appspot.com/slack/receive
I have no answer. 
What I've found so fare:
- When I try to GET any url, the web server is answering fine
- When I POST any thing to any url, the server is not responding

Any ideas?
(Please note that I'm not using botkit studio, so I don't have any botkit token).

**Comment by peterswimm** [comment]
This needs to be an HTTPS url, does gcloud provide that?

**Comment by starpause** [comment]
Does a manual post to your application yield any results? If not it sounds like a Google Cloud Platform issue rather than anything related to botkit. See https://cloud.google.com/appengine/docs/standard/php/issue-requests
