### ISSUE TITLE
I experienced an error with a request to Botkit Studio:

### ISSUE THREAD

**Issue by manishsakhare** [howdyai/botkit-starter-slack#22]
[object Object] ...... i m getting this error when m posting something to my bot in slack can some one help?? thanks

**Comment by peterswimm** [comment]
What error specifically? Have you made any modifications to the starter kit code?

**Comment by manishsakhare** [comment]
no sir i have just created bot and added to my slack.. i didn't done any
modification.. and if i type something in my bot i get above error.. pls
help.. thanks..!!!

**Comment by peterswimm** [comment]
Where are you running your bot? Can you post a screenshot of the exact errors?

**Comment by manishsakhare** [comment]
Fixed it sir.. Thanx..
I have one another problem.. can we integrate botkit with api.ai?

**Comment by peterswimm** [comment]
Yes, with the following middleware https://github.com/abeai/botkit-middleware-apiai

**Comment by manishsakhare** [comment]
Thanks

**Comment by refai2016** [comment]
I am having the same issue. Can you please explain how it was fixed for you?
@manishsakhare
