### ISSUE TITLE
Require

### ISSUE THREAD

**Issue by srepollock** [howdyai/botkit-starter-slack#5]
I can't seem to get my `require("./skills/" + file)(controller)` working. I have the same `bot.js` file as you and the same dependencies in my `package.json` file. I can't find any resources to help me with the issue.

Is there something I'm missing?

**Comment by benbrown** [comment]
@srepollock did you ever get this issue sorted out?

**Comment by srepollock** [comment]
Haven't looked in a while. I'll take a look sometime this week and let you know
